id: 17647d54a75d437caad9e727a67d51cc
initial_creation_type: ocr
source_metadata:
  volumes:
    d1a4e6d6ea504592a37f9ffb0d3b357e:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
